"""KI-Rezeptbibliothek – 250+ vorgefertigte KI-Aufgaben für die ADB-Shell."""

RECIPES = {
    '🔍 Diagnose & Fehlersuche': [
        'Warum entlädt sich der Akku über Nacht so schnell?',
        'Welche App verursacht die meiste CPU-Last?',
        'Warum ist das Gerät heiß geworden?',
        'Finde die Ursache für Ruckler/Lags',
        'Welche App hält das Gerät wach (Wakelock)?',
        'Warum stürzt App X ständig ab?',
        'Analysiere den letzten Absturz im Logcat',
        'Warum ist der Speicher voll?',
        'Welche App verbraucht das meiste mobile Datenvolumen?',
        'Warum lädt das Gerät so langsam?',
        'Finde Apps die im Hintergrund Standort abfragen',
        'Warum reagiert der Touchscreen verzögert?',
        'Welcher Dienst frisst RAM?',
        'Warum verbindet sich WLAN nicht?',
        'Analysiere Bluetooth-Verbindungsabbrüche',
        'Warum kommen Benachrichtigungen verspätet?',
        'Finde Apps die den Doze-Modus verhindern',
        'Warum ist die Kamera langsam beim Start?',
        'Analysiere die Boot-Zeit und was sie verlangsamt',
        'Welche App weckt das Gerät am häufigsten?',
    ],
    '⚡ Performance-Optimierung': [
        'Mache das Gerät schneller (Animationen, Cache)',
        'Reduziere Hintergrundprozesse',
        'Leere alle App-Caches sicher',
        'Finde und stoppe unnötige Autostart-Apps',
        'Optimiere die RAM-Nutzung',
        'Beschleunige App-Starts',
        'Reduziere den Akkuverbrauch systemweit',
        'Deaktiviere unnötige Sync-Adapter',
        'Finde Apps die nie genutzt werden',
        'Optimiere die Display-Einstellungen für Akku',
        'Schalte Animationen komplett aus',
        'Begrenze Hintergrunddaten der Top-Verbraucher',
        'Identifiziere und beende Zombie-Prozesse',
        'Optimiere die WLAN-Scan-Frequenz',
        'Reduziere die GPS-Abfragehäufigkeit',
    ],
    '🧹 Aufräumen & Speicher': [
        'Finde die größten Speicherfresser',
        'Liste verwaiste Dateien und Caches',
        'Finde doppelte Fotos/Dateien',
        'Zeige alte heruntergeladene Dateien',
        'Finde leere Ordner zum Aufräumen',
        'Liste alle Log-/Temp-Dateien',
        'Finde große Video-Dateien',
        'Zeige App-Datenverbrauch sortiert',
        'Finde alte WhatsApp-Medien',
        'Liste Thumbnails und Vorschau-Caches',
    ],
    '🛡️ Sicherheit & Datenschutz': [
        'Finde Apps mit gefährlichen Berechtigungen',
        'Erkenne mögliche Spyware/Stalkerware',
        'Prüfe welche Apps Mikrofon-Zugriff haben',
        'Prüfe welche Apps Kamera-Zugriff haben',
        'Finde Apps die SMS lesen können',
        'Prüfe aktive Accessibility-Dienste',
        'Finde Apps mit Geräte-Admin-Rechten',
        'Prüfe ob unbekannte Quellen erlaubt sind',
        'Analysiere Apps die im Hintergrund senden',
        'Finde Apps mit Overlay-Berechtigung',
        'Prüfe den Verschlüsselungsstatus',
        'Liste alle Apps mit Standortzugriff',
        'Finde Apps die andere Apps auslesen (QUERY_ALL)',
        'Prüfe installierte Zertifikate',
        'Finde Apps ohne Play-Store-Herkunft',
        'Analysiere Netzwerkverbindungen auf verdächtige Ziele',
        'Prüfe ob ADB-WLAN aktiv ist',
        'Finde Apps die Benachrichtigungen aller Apps lesen',
        'Prüfe Sperrbildschirm-Sicherheit',
        'Analysiere die Berechtigungs-Historie',
    ],
    '📱 App-Management': [
        'Liste alle installierten Apps mit Größe',
        'Finde Bloatware zum Deaktivieren',
        'Zeige System-Apps die deaktivierbar sind',
        'Finde Apps die nie geöffnet wurden',
        'Liste Apps nach Installationsdatum',
        'Zeige zuletzt aktualisierte Apps',
        'Finde Apps mit den meisten Berechtigungen',
        'Liste Apps die Autostart nutzen',
        'Zeige welche App welche Activity exportiert',
        'Finde Apps die Standard-Handler sind',
        'Liste alle Launcher-Alternativen',
        'Zeige Apps die Benachrichtigungen senden dürfen',
        'Finde Apps die Batterie-Optimierung umgehen',
        'Liste Apps mit Hintergrund-Standort',
        'Zeige deaktivierte Apps',
    ],
    '🌐 Netzwerk & Verbindung': [
        'Zeige alle aktiven Netzwerkverbindungen',
        'Analysiere die WLAN-Signalstärke',
        'Liste gespeicherte WLAN-Netze',
        'Zeige die DNS-Einstellungen',
        'Prüfe ob ein Proxy gesetzt ist',
        'Analysiere den mobilen Datenverbrauch pro App',
        'Zeige die aktuelle IP-Konfiguration',
        'Liste offene Ports',
        'Prüfe VPN-Status',
        'Teste die Internetverbindung',
        'Zeige Bluetooth-gekoppelte Geräte',
        'Analysiere die Mobilfunk-Signalqualität',
        'Setze einen privaten DNS-Server',
        'Zeige die ARP-Tabelle (Geräte im Netz)',
        'Prüfe ob Datenroaming aktiv ist',
    ],
    '🔧 System-Tweaks': [
        'Aktiviere den Dark Mode systemweit',
        'Ändere die Display-Auflösung/DPI',
        'Schalte alle Animationen aus',
        'Aktiviere Entwickleroptionen-Tweaks',
        'Ändere die Zeitzone',
        'Aktiviere den 90Hz/120Hz-Modus falls möglich',
        'Erzwinge GPU-Rendering',
        'Zeige die FPS auf dem Bildschirm',
        'Aktiviere den immersiven Vollbildmodus',
        'Ändere die Standard-Tastatur',
        'Setze die Animationsskalierung',
        'Aktiviere/Deaktiviere Auto-Rotation',
        'Ändere die Schriftgröße per Befehl',
        'Aktiviere den Einhandmodus',
        'Erzwinge RTL-Layout zum Testen',
    ],
    '📊 Forensik & Analyse': [
        'Erstelle eine Aktivitäts-Timeline der letzten Stunden',
        'Zeige wann welche App zuletzt geöffnet wurde',
        'Analysiere die Anruf-Muster',
        'Zeige die SMS-Statistik',
        'Liste alle Konten und ihre Sync-Zeiten',
        'Erstelle ein Bewegungsprofil aus Standortdaten',
        'Zeige die Browser-Aktivität',
        'Analysiere die Mediendateien nach Zeit',
        'Zeige die Installations-Historie',
        'Finde Hinweise auf gelöschte Daten',
        'Erstelle einen Geräte-Identitäts-Report',
        'Analysiere die Benachrichtigungs-Historie',
        'Zeige die häufigsten Kontakte',
        'Erstelle eine WLAN-Verbindungs-Historie',
        'Analysiere die Akku-Nutzung über die Zeit',
    ],
    '🎮 Automatisierung & Steuerung': [
        'Mache einen Screenshot und speichere ihn',
        'Nimm den Bildschirm als Video auf',
        'Simuliere einen Tastendruck (Home/Zurück)',
        'Tippe einen Text in das aktive Feld',
        'Scrolle durch die aktuelle App',
        'Öffne eine bestimmte App',
        'Sende das Gerät in den Standby',
        'Wecke das Gerät auf',
        'Schalte WLAN/Bluetooth per Befehl',
        'Starte eine App und messe die Startzeit',
        'Simuliere einen Swipe',
        'Öffne eine URL im Browser',
        'Setze die Lautstärke',
        'Aktiviere den Flugmodus',
        'Mache einen UI-Dump der aktuellen Ansicht',
    ],
    '💾 Backup & Wiederherstellung': [
        'Sichere alle Fotos auf den PC',
        'Erstelle ein App-Listen-Backup',
        'Sichere die SMS-Datenbank',
        'Exportiere die Kontakte',
        'Sichere die Anrufliste',
        'Erstelle ein Backup der WhatsApp-Medien',
        'Sichere die App-Einstellungen einer App',
        'Exportiere die WLAN-Konfiguration',
        'Sichere die Kalender-Termine',
        'Erstelle ein vollständiges Geräte-Inventar',
    ],
    '📡 Mobilfunk & SIM': [
        'Zeige die aktuelle Funkzelle (Cell-ID)',
        'Analysiere die Nachbarzellen',
        'Prüfe den VoLTE/VoWiFi-Status',
        'Zeige die SIM-Informationen',
        'Liste die APN-Einstellungen',
        'Prüfe den Netzbetreiber und das Land',
        'Zeige die Signalstärke in dBm',
        'Analysiere den Netztyp (4G/5G)',
        'Prüfe den Roaming-Status',
        'Zeige die IMSI/IMEI falls lesbar',
        'Überwache Zellenwechsel',
        'Prüfe auf 2G-Downgrade (Sicherheit)',
        'Zeige die Baseband-Version',
        'Analysiere die Mobilfunk-Historie',
        'Prüfe die VoNR/5G-Konfiguration',
    ],
    '🩺 Hardware-Diagnose': [
        'Teste alle Sensoren (Gyro/Beschleunigung)',
        'Zeige die Akku-Gesundheit',
        'Prüfe die CPU-Temperatur',
        'Zeige die Display-Spezifikationen',
        'Teste das Mikrofon',
        'Prüfe die Lautsprecher',
        'Zeige die Kamera-Spezifikationen',
        'Analysiere die Akku-Lade-/Entladerate',
        'Prüfe den verfügbaren Speicher',
        'Zeige die RAM-Auslastung',
        'Teste den Helligkeitssensor',
        'Prüfe die GPS-Genauigkeit',
        'Zeige die Thermalsensoren',
        'Analysiere die CPU-Frequenzen pro Kern',
        'Prüfe den NFC-Status',
    ],
    '🔓 Root & Modding (falls Root)': [
        'Prüfe ob das Gerät gerootet ist',
        'Zeige den Magisk-Status',
        'Liste installierte Magisk-Module',
        'Prüfe den SELinux-Status',
        'Sichere die boot-Partition',
        'Zeige die Partitionstabelle',
        'Mounte /system als beschreibbar',
        'Lies geschützte System-Properties',
        'Zeige den Bootloader-Status',
        'Prüfe den Verified-Boot-Status',
    ],
    '📂 Datei-Operationen': [
        'Finde alle PDF-Dokumente',
        'Liste alle Bilder mit Aufnahmedatum',
        'Finde Dateien die heute geändert wurden',
        'Zeige versteckte Dateien und Ordner',
        'Finde alle Audio-Dateien',
        'Liste Dateien größer als 100MB',
        'Finde .nomedia-Ordner',
        'Zeige die Ordnerstruktur von /sdcard',
        'Finde alle ZIP/Archiv-Dateien',
        'Liste kürzlich erstellte Screenshots',
        'Finde alle APK-Dateien auf dem Gerät',
        'Zeige Dateien in Download sortiert nach Datum',
        'Finde temporäre Dateien zum Löschen',
        'Liste alle Datenbank-Dateien (sichtbar)',
        'Zeige die größten Ordner',
    ],
    '📞 Kommunikation': [
        'Zeige die letzten eingehenden Anrufe',
        'Liste verpasste Anrufe',
        'Zeige die längsten Telefonate',
        'Analysiere mit wem am meisten telefoniert wird',
        'Liste alle SMS der letzten Woche',
        'Finde SMS mit Verifizierungscodes',
        'Zeige unbekannte Nummern in der Anrufliste',
        'Liste blockierte Nummern',
        'Zeige die SMS-Statistik nach Absender',
        'Finde Spam-verdächtige SMS',
    ],
    '🖼️ Medien & Fotos': [
        'Zeige alle Screenshots der letzten Woche',
        'Finde Fotos mit GPS-Standort',
        'Liste Videos sortiert nach Länge',
        'Zeige die neuesten Kamera-Aufnahmen',
        'Finde Fotos von einer bestimmten App (z.B. WhatsApp)',
        'Analysiere die Foto-Aufnahmezeiten (Tagesmuster)',
        'Zeige alle Sprachaufnahmen',
        'Liste Musik-Dateien mit Metadaten',
        'Finde Bildschirmaufnahmen',
        'Zeige die Foto-Speicherorte',
    ],
    '🧪 Entwickler & Debug': [
        'Zeige den aktuellen Activity-Stack',
        'Dumpe die UI-Hierarchie der aktuellen App',
        'Zeige laufende Services',
        'Liste registrierte Broadcast-Receiver',
        'Zeige den Logcat gefiltert nach Fehlern',
        'Analysiere ANRs (App Not Responding)',
        'Zeige die Intent-Filter einer App',
        'Dumpe die SharedPreferences-Struktur (sichtbar)',
        'Zeige GPU-Rendering-Profil einer App',
        'Liste alle Content-Provider',
        'Zeige die Speicher-Details einer App (meminfo)',
        'Analysiere die Frame-Render-Zeiten',
        'Zeige die Wakelock-Statistik',
        'Liste alle System-Properties',
        'Zeige den Batterie-Verlauf detailliert',
    ],
    '🤖 KI-Kreativ & Sonstiges': [
        'Erkläre mir was dieses Gerät über mich verrät',
        'Erstelle einen Sicherheits-Gesamtbericht',
        'Bewerte die Privatsphäre-Lage des Geräts',
        'Gib mir 5 Tipps zur Akku-Verlängerung',
        'Erkläre die verdächtigsten Apps in einfachen Worten',
        'Erstelle eine Zusammenfassung der Geräte-Nutzung',
        'Schlage vor was ich deinstallieren sollte',
        'Erkläre welche Daten Google von mir synct',
        'Erstelle einen Forensik-Bericht für dieses Gerät',
        'Was würde ein Angreifer auf diesem Gerät zuerst suchen?',
        "Bewerte wie 'sauber' das Gerät ist (1-10)",
        'Erkläre die Bedeutung der aktiven Sync-Dienste',
        'Was verraten die App-Berechtigungen über die Nutzung?',
        'Erstelle eine To-Do-Liste zur Geräte-Absicherung',
        'Vergleiche dieses Gerät mit Sicherheits-Best-Practices',
    ],
}

TOTAL = 255